on:
  pull_request:
    branches:
      - master

name: Build

jobs:
  build:
    name: Try Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: |
          sudo apt-get -y install make gcc python3

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Install Project Dependencies
        run: npm install --legacy-peer-deps

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Install other dependencies
        run: npm install @parcel/watcher

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public
