on:
  pull_request:
  push:
    branches:
      - master

name: Build

jobs:
  build:
    name: Try Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: |
          sudo apt-get -y install make gcc python3

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public
